#!/bin/bash

die () { echo "$@" >&2; exit 1; }

# From https://www.tensorflow.org/install/install_linux#InstallingVirtualenv .

sudo apt install python3-pip python3-dev python-virtualenv

[ -d venv ] || virtualenv --system-site-packages -p python3 venv

. venv/bin/activate

pip install -U pip

pip install -U -r requirements.txt

[ -d tf-models ] || \
    git clone https://github.com/gnprice/tf-models
[ -d ptb-data ] || {
    mkdir ptb-data
    curl http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz \
        | tar -C ptb-data --strip-components=3 -x ./simple-examples/data/
}

cat <<EOF
Provision complete!

To use:

  . venv/bin/activate
EOF
